- hosts: web
  become: yes
  tasks:

    - name: Stop old container
      shell: docker stop springboot-container || true

    - name: Remove old container
      shell: docker rm springboot-container || true

    - name: Remove old image
      shell: docker rmi lohar45/ansible_jek_pro:latest || true

    - name: Pull latest image
      shell: docker pull lohar45/ansible_jek_pro:latest

    - name: Run container
      shell: docker run -d -p 8080:8080 --name springboot-container lohar45/ansible_jek_pro:latest
