---
- hosts: all
  become: true

  tasks:

    - name: Pull latest Docker image
      community.docker.docker_container:
        name: spring_container
        image: lohar45/akshay-ansibl:latest
        state: started
        restart_policy: always
        recreate: true
        ports:
          - "8085:8080"
